# Generated by Django 4.1.1 on 2022-09-18 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=20, unique=True)),
                ("type", models.CharField(max_length=16)),
                ("merchant_id", models.CharField(max_length=20, unique=True)),
                ("merchant_name", models.CharField(max_length=100)),
                ("merchant_country", models.CharField(max_length=4)),
                (
                    "merchant_city",
                    models.CharField(default=None, max_length=128, null=True),
                ),
                ("merchant_mcc", models.IntegerField()),
                (
                    "billing_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("billing_currency", models.CharField(max_length=3)),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("transaction_currency", models.CharField(max_length=3)),
                (
                    "settlement_amount",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=10, null=True
                    ),
                ),
                (
                    "settlement_currency",
                    models.CharField(default=None, max_length=3, null=True),
                ),
                ("settled", models.BooleanField(default=False)),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        blank=True,
                        choices=[("CRT", "Credit"), ("DBT", "Debit")],
                        max_length=3,
                    ),
                ),
                ("total_balance", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.transaction",
                        to_field="transaction_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(default="", max_length=30)),
                ("business_name", models.CharField(default="", max_length=250)),
                ("business_type", models.CharField(max_length=255)),
                ("merchant_address", models.CharField(max_length=255)),
                ("merchant_city", models.CharField(default="Dubai", max_length=128)),
                ("merchant_country", models.CharField(default="UAE", max_length=50)),
                ("bank_account", models.CharField(max_length=30)),
                ("bank_country", models.CharField(default="", max_length=30)),
                ("card_id", models.CharField(max_length=20, unique=True)),
                ("merchant_id", models.CharField(default="", max_length=30)),
                ("currency", models.CharField(max_length=3)),
                (
                    "total_balance",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "available_balance",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "reserved_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
