# Generated by Django 4.1.1 on 2022-09-18 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=20, unique=True)),
                ("type", models.CharField(max_length=16)),
                ("merchant_id", models.CharField(max_length=20, unique=True)),
                ("merchant_name", models.CharField(max_length=100)),
                ("merchant_country", models.CharField(max_length=4)),
                (
                    "merchant_city",
                    models.CharField(default=None, max_length=128, null=True),
                ),
                ("merchant_mcc", models.IntegerField()),
                (
                    "billing_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("billing_currency", models.CharField(max_length=3)),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("transaction_currency", models.CharField(max_length=3)),
                (
                    "settlement_amount",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=10, null=True
                    ),
                ),
                (
                    "settlement_currency",
                    models.CharField(default=None, max_length=3, null=True),
                ),
                ("settled", models.BooleanField(default=False)),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        blank=True,
                        choices=[("CRT", "Credit"), ("DBT", "Debit")],
                        max_length=3,
                    ),
                ),
                ("total_balance", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.transaction",
                        to_field="transaction_id",
                    ),
                ),
            ],
        ),
    ]
