# Generated by Django 4.1.1 on 2022-09-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="merchant_id",
            field=models.CharField(default="N2DFZQUB", max_length=30),
        ),
    ]
