# Generated by Django 4.1.1 on 2022-09-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_merchant_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="merchant_id",
            field=models.DecimalField(
                decimal_places=0, default="83126079", max_digits=10
            ),
        ),
    ]
