# Generated by Django 4.1.1 on 2022-09-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_customuser_username_alter_profile_merchant_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.PositiveIntegerField()),
                ("merchant_id", models.CharField(max_length=255)),
                ("merchant_name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("number_of_products", models.CharField(max_length=255)),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_address", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField()),
                ("product_name", models.CharField(max_length=255)),
                ("merchant_name", models.CharField(max_length=255)),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="merchant_city",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="merchant_country",
        ),
        migrations.AlterField(
            model_name="profile",
            name="merchant_id",
            field=models.DecimalField(
                decimal_places=0, default="35790268", max_digits=10
            ),
        ),
    ]
