# Generated by Django 4.1.1 on 2022-09-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_order_product_remove_transaction_merchant_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="merchant_id",
            field=models.DecimalField(
                decimal_places=0, default="17423058", max_digits=10
            ),
        ),
    ]
