# Generated by Django 4.1.1 on 2022-09-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_order_product_name_alter_profile_merchant_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="merchant_id",
            field=models.DecimalField(
                decimal_places=0, default="45308926", max_digits=10
            ),
        ),
    ]
