# Generated by Django 4.1.1 on 2023-08-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_merchant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='merchant_id',
            field=models.DecimalField(decimal_places=0, default='19450327', max_digits=10),
        ),
    ]
