# Generated by Django 4.1.1 on 2022-09-14 21:51

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                ("merchant_name", models.CharField(max_length=30)),
                (
                    "merchant_id",
                    models.CharField(default="GPM-VAQZ719B-2022", max_length=32),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_account", models.CharField(max_length=30)),
                ("bank_country", models.CharField(max_length=100)),
                ("card_id", models.IntegerField()),
                ("merchant_id", models.IntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("total_balance", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "available_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "reserved_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "merchant_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=20, unique=True)),
                ("type", models.CharField(max_length=16)),
                ("merchant_id", models.CharField(max_length=20, unique=True)),
                ("merchant_name", models.CharField(max_length=100)),
                ("merchant_country", models.CharField(max_length=4)),
                (
                    "merchant_city",
                    models.CharField(default=None, max_length=128, null=True),
                ),
                ("merchant_mcc", models.IntegerField()),
                (
                    "billing_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("billing_currency", models.CharField(max_length=3)),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("transaction_currency", models.CharField(max_length=3)),
                (
                    "settlement_amount",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=10, null=True
                    ),
                ),
                (
                    "settlement_currency",
                    models.CharField(default=None, max_length=3, null=True),
                ),
                ("settled", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        blank=True,
                        choices=[("CRT", "Credit"), ("DBT", "Debit")],
                        max_length=3,
                    ),
                ),
                ("total_balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "merchant_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="payapi.account"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payapi.transaction",
                        to_field="transaction_id",
                    ),
                ),
            ],
        ),
    ]
