# Generated by Django 4.1.1 on 2022-09-14 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credit_card_id", models.CharField(max_length=20, unique=True)),
                ("currency", models.CharField(max_length=3)),
                ("total_balance", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "available_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "reserved_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=30)),
                ("bank_account", models.CharField(max_length=30)),
                ("bank_country", models.CharField(max_length=100)),
                ("credit_card_id", models.IntegerField()),
                ("total_balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=20, unique=True)),
                ("type", models.CharField(max_length=16)),
                ("merchant_name", models.CharField(max_length=100)),
                ("merchant_country", models.CharField(max_length=4)),
                (
                    "merchant_city",
                    models.CharField(default=None, max_length=128, null=True),
                ),
                ("merchant_mcc", models.IntegerField()),
                (
                    "billing_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("billing_currency", models.CharField(max_length=3)),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("transaction_currency", models.CharField(max_length=3)),
                (
                    "settlement_amount",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=10, null=True
                    ),
                ),
                (
                    "settlement_currency",
                    models.CharField(default=None, max_length=3, null=True),
                ),
                ("settled", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "credit_card_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payapi.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        blank=True,
                        choices=[("CRT", "Credit"), ("DBT", "Debit")],
                        max_length=3,
                    ),
                ),
                ("total_balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="payapi.account"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payapi.transaction",
                        to_field="transaction_id",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="card_id",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cardpi",
                to="payapi.customer",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="customer_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="payapi.customer"
            ),
        ),
    ]
