# Generated by Django 4.1.1 on 2022-09-15 23:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("merchant_name", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("business_type", models.CharField(max_length=255)),
                ("merchant_address", models.CharField(max_length=255)),
                ("merchant_city", models.CharField(default="Dubai", max_length=128)),
                ("merchant_country", models.CharField(default="UAE", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_account", models.CharField(max_length=30)),
                ("bank_country", models.CharField(default="", max_length=30)),
                ("card_id", models.CharField(max_length=20, unique=True)),
                ("merchant_id", models.CharField(default="", max_length=30)),
                ("currency", models.CharField(max_length=3)),
                ("total_balance", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "available_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "reserved_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=20, unique=True)),
                ("type", models.CharField(max_length=16)),
                ("merchant_id", models.CharField(max_length=20, unique=True)),
                ("merchant_name", models.CharField(max_length=100)),
                ("merchant_country", models.CharField(max_length=4)),
                (
                    "merchant_city",
                    models.CharField(default=None, max_length=128, null=True),
                ),
                ("merchant_mcc", models.IntegerField()),
                (
                    "billing_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("billing_currency", models.CharField(max_length=3)),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("transaction_currency", models.CharField(max_length=3)),
                (
                    "settlement_amount",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=10, null=True
                    ),
                ),
                (
                    "settlement_currency",
                    models.CharField(default=None, max_length=3, null=True),
                ),
                ("settled", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        blank=True,
                        choices=[("CRT", "Credit"), ("DBT", "Debit")],
                        max_length=3,
                    ),
                ),
                ("total_balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "transaction",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payapi.transaction",
                        to_field="transaction_id",
                    ),
                ),
            ],
        ),
    ]
