# Generated by Django 4.1.1 on 2022-09-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="merchant_id",
            field=models.CharField(default="GPM-G1MBQ5OP-2022", max_length=32),
        ),
    ]
