# Generated by Django 4.1.1 on 2022-09-16 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payapi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="is_active",
        ),
    ]
