# Generated by Django 4.1.1 on 2022-09-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="merchant_city",
            field=models.CharField(default="Dubai", max_length=128),
        ),
        migrations.AddField(
            model_name="merchant",
            name="merchant_country",
            field=models.CharField(default="UAE", max_length=50),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="merchant_id",
            field=models.CharField(default="GPM-489BOGK5-2022", max_length=32),
        ),
    ]
