# Generated by Django 4.1.1 on 2022-09-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="card_id",
            field=models.CharField(max_length=16),
        ),
    ]
