# Generated by Django 4.1.1 on 2022-09-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapi", "0002_merchant_merchant_city_merchant_merchant_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="merchant_id",
            field=models.CharField(default="GPM-LY8HR3OX-2022", max_length=32),
        ),
    ]
