# Generated by Django 4.1.1 on 2022-09-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapi", "0002_alter_user_email_alter_user_merchant_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="merchant_id",
        ),
        migrations.AlterField(
            model_name="profile",
            name="merchant_id",
            field=models.CharField(default="GPM-YWANXTPI-2022", max_length=32),
        ),
    ]
