# Generated by Django 4.1.1 on 2022-09-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapi", "0002_alter_account_card_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="credit_card_id",
            field=models.IntegerField(null=True),
        ),
    ]
