# Generated by Django 4.1.1 on 2022-09-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapi", "0003_myuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="myuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
