# Generated by Django 4.1.1 on 2022-09-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapi", "0003_alter_transaction_credit_card_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="card_id",
            field=models.IntegerField(),
        ),
    ]
