# Generated by Django 4.1.1 on 2022-09-16 17:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payapi", "0004_myuser_is_staff_myuser_is_superuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="business_type",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="merchant_address",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="merchant_city",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="merchant_country",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="merchant_name",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="available_balance",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="bank_account",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="bank_country",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="card_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="merchant_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="reserved_amount",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="total_balance",
        ),
        migrations.AddField(
            model_name="myuser",
            name="created",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="admin"),
        ),
        migrations.AddField(
            model_name="myuser",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Homme"), ("F", "Femme")], default="", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="zip_code",
            field=models.CharField(
                default="",
                max_length=5,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
    ]
